//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpAssignment.CriminalServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriminalModel", Namespace="http://schemas.datacontract.org/2004/07/CSharpAssignment.Services.Models")]
    [System.SerializableAttribute()]
    public partial class CriminalModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ConvictedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrimeTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HeightInCmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MinHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MinWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WeightInPoundsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgeRange {
            get {
                return this.AgeRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeRangeField, value) != true)) {
                    this.AgeRangeField = value;
                    this.RaisePropertyChanged("AgeRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ConvictedOn {
            get {
                return this.ConvictedOnField;
            }
            set {
                if ((this.ConvictedOnField.Equals(value) != true)) {
                    this.ConvictedOnField = value;
                    this.RaisePropertyChanged("ConvictedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Crime {
            get {
                return this.CrimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CrimeField, value) != true)) {
                    this.CrimeField = value;
                    this.RaisePropertyChanged("Crime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrimeTypeId {
            get {
                return this.CrimeTypeIdField;
            }
            set {
                if ((this.CrimeTypeIdField.Equals(value) != true)) {
                    this.CrimeTypeIdField = value;
                    this.RaisePropertyChanged("CrimeTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HeightInCms {
            get {
                return this.HeightInCmsField;
            }
            set {
                if ((this.HeightInCmsField.Equals(value) != true)) {
                    this.HeightInCmsField = value;
                    this.RaisePropertyChanged("HeightInCms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxHeight {
            get {
                return this.MaxHeightField;
            }
            set {
                if ((this.MaxHeightField.Equals(value) != true)) {
                    this.MaxHeightField = value;
                    this.RaisePropertyChanged("MaxHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxWeight {
            get {
                return this.MaxWeightField;
            }
            set {
                if ((this.MaxWeightField.Equals(value) != true)) {
                    this.MaxWeightField = value;
                    this.RaisePropertyChanged("MaxWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MinHeight {
            get {
                return this.MinHeightField;
            }
            set {
                if ((this.MinHeightField.Equals(value) != true)) {
                    this.MinHeightField = value;
                    this.RaisePropertyChanged("MinHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MinWeight {
            get {
                return this.MinWeightField;
            }
            set {
                if ((this.MinWeightField.Equals(value) != true)) {
                    this.MinWeightField = value;
                    this.RaisePropertyChanged("MinWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WeightInPounds {
            get {
                return this.WeightInPoundsField;
            }
            set {
                if ((this.WeightInPoundsField.Equals(value) != true)) {
                    this.WeightInPoundsField = value;
                    this.RaisePropertyChanged("WeightInPounds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationModel", Namespace="http://schemas.datacontract.org/2004/07/CSharpAssignment.Services.Models")]
    [System.SerializableAttribute()]
    public partial class LocationModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrimeTypeModel", Namespace="http://schemas.datacontract.org/2004/07/CSharpAssignment.Services.Models")]
    [System.SerializableAttribute()]
    public partial class CrimeTypeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrimeTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrimeTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrimeTypeId {
            get {
                return this.CrimeTypeIdField;
            }
            set {
                if ((this.CrimeTypeIdField.Equals(value) != true)) {
                    this.CrimeTypeIdField = value;
                    this.RaisePropertyChanged("CrimeTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrimeTypeName {
            get {
                return this.CrimeTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CrimeTypeNameField, value) != true)) {
                    this.CrimeTypeNameField = value;
                    this.RaisePropertyChanged("CrimeTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/CSharpAssignment.Services")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CriminalServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCriminalSearchDetails", ReplyAction="http://tempuri.org/IService1/GetCriminalSearchDetailsResponse")]
        CSharpAssignment.CriminalServiceReference.CriminalModel[] GetCriminalSearchDetails(CSharpAssignment.CriminalServiceReference.CriminalModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCriminalSearchDetails", ReplyAction="http://tempuri.org/IService1/GetCriminalSearchDetailsResponse")]
        System.Threading.Tasks.Task<CSharpAssignment.CriminalServiceReference.CriminalModel[]> GetCriminalSearchDetailsAsync(CSharpAssignment.CriminalServiceReference.CriminalModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLocations", ReplyAction="http://tempuri.org/IService1/GetLocationsResponse")]
        CSharpAssignment.CriminalServiceReference.LocationModel[] GetLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLocations", ReplyAction="http://tempuri.org/IService1/GetLocationsResponse")]
        System.Threading.Tasks.Task<CSharpAssignment.CriminalServiceReference.LocationModel[]> GetLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCrimeTypes", ReplyAction="http://tempuri.org/IService1/GetCrimeTypesResponse")]
        CSharpAssignment.CriminalServiceReference.CrimeTypeModel[] GetCrimeTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCrimeTypes", ReplyAction="http://tempuri.org/IService1/GetCrimeTypesResponse")]
        System.Threading.Tasks.Task<CSharpAssignment.CriminalServiceReference.CrimeTypeModel[]> GetCrimeTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        CSharpAssignment.CriminalServiceReference.CompositeType GetDataUsingDataContract(CSharpAssignment.CriminalServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CSharpAssignment.CriminalServiceReference.CompositeType> GetDataUsingDataContractAsync(CSharpAssignment.CriminalServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CSharpAssignment.CriminalServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CSharpAssignment.CriminalServiceReference.IService1>, CSharpAssignment.CriminalServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSharpAssignment.CriminalServiceReference.CriminalModel[] GetCriminalSearchDetails(CSharpAssignment.CriminalServiceReference.CriminalModel model) {
            return base.Channel.GetCriminalSearchDetails(model);
        }
        
        public System.Threading.Tasks.Task<CSharpAssignment.CriminalServiceReference.CriminalModel[]> GetCriminalSearchDetailsAsync(CSharpAssignment.CriminalServiceReference.CriminalModel model) {
            return base.Channel.GetCriminalSearchDetailsAsync(model);
        }
        
        public CSharpAssignment.CriminalServiceReference.LocationModel[] GetLocations() {
            return base.Channel.GetLocations();
        }
        
        public System.Threading.Tasks.Task<CSharpAssignment.CriminalServiceReference.LocationModel[]> GetLocationsAsync() {
            return base.Channel.GetLocationsAsync();
        }
        
        public CSharpAssignment.CriminalServiceReference.CrimeTypeModel[] GetCrimeTypes() {
            return base.Channel.GetCrimeTypes();
        }
        
        public System.Threading.Tasks.Task<CSharpAssignment.CriminalServiceReference.CrimeTypeModel[]> GetCrimeTypesAsync() {
            return base.Channel.GetCrimeTypesAsync();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public CSharpAssignment.CriminalServiceReference.CompositeType GetDataUsingDataContract(CSharpAssignment.CriminalServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<CSharpAssignment.CriminalServiceReference.CompositeType> GetDataUsingDataContractAsync(CSharpAssignment.CriminalServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
